# Generates source/tyControls.BuiltinSkins.pas from themes/builtin/*.tycss.
# Each skin's CSS is compiled in + registered by name, so apps ship the skins with no themes/ folder.
# Edit themes/builtin/*.tycss, then re-run this; test.builtinskins guards that the two stay in sync.
$root = 'D:\Projects\ty-controls'
$dir  = Join-Path $root 'themes\builtin'
$out  = Join-Path $root 'source\tyControls.BuiltinSkins.pas'
$enc  = New-Object System.Text.UTF8Encoding($false)

$files = Get-ChildItem (Join-Path $dir '*.tycss') | Sort-Object Name
$names = @()

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('unit tyControls.BuiltinSkins;')
[void]$sb.AppendLine('{ The structural skins (classic, xp, office, win11, ...) compiled IN from themes/builtin/*.tycss,')
[void]$sb.AppendLine('  so an app ships them without a themes/ folder. GENERATED by gen-builtinskins.ps1 -- do NOT edit')
[void]$sb.AppendLine('  by hand; edit themes/builtin/<name>.tycss then re-run the generator. test.builtinskins guards')
[void]$sb.AppendLine('  that each compiled-in const stays byte-identical to its file. }')
[void]$sb.AppendLine('{$mode objfpc}{$H+}')
[void]$sb.AppendLine('interface')
[void]$sb.AppendLine('uses Classes, SysUtils;')
[void]$sb.AppendLine('{ Register every built-in structural skin by name (via TyRegisterThemeCss), so ThemeName := ''office''')
[void]$sb.AppendLine('  etc. resolves with no file. Idempotent; call from TyRegisterBuiltinThemes. }')
[void]$sb.AppendLine('procedure TyRegisterBuiltinSkins;')
[void]$sb.AppendLine('{ The built-in skin names (sorted), for a host to populate a theme picker. }')
[void]$sb.AppendLine('function TyBuiltinSkinNames: TStringArray;')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('implementation')
[void]$sb.AppendLine('uses tyControls.ThemeRegistry;')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('procedure TyRegisterBuiltinSkins;')
[void]$sb.AppendLine('begin')
foreach ($f in $files) {
  $name = [System.IO.Path]::GetFileNameWithoutExtension($f.Name)
  $names += $name
  $text = [System.IO.File]::ReadAllText($f.FullName, [System.Text.Encoding]::UTF8)
  $lines = $text -split "`r?`n"
  if ($lines.Count -gt 0 -and $lines[$lines.Count-1] -eq '') { $lines = $lines[0..($lines.Count-2)] }
  [void]$sb.AppendLine("  TyRegisterThemeCss('$name',")
  for ($i = 0; $i -lt $lines.Count; $i++) {
    $ln = $lines[$i].Replace("'", "''")
    if ($i -lt $lines.Count - 1) { $term = ' + LineEnding +' } else { $term = ');' }
    [void]$sb.AppendLine("    '" + $ln + "'" + $term)
  }
}
[void]$sb.AppendLine('end;')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('function TyBuiltinSkinNames: TStringArray;')
$arr = ($names | ForEach-Object { "'$_'" }) -join ', '
[void]$sb.AppendLine("const N: array[0..$($names.Count-1)] of string = ($arr);")
[void]$sb.AppendLine('var i: Integer;')
[void]$sb.AppendLine('begin')
[void]$sb.AppendLine('  SetLength(Result, Length(N));')
[void]$sb.AppendLine('  for i := 0 to High(N) do Result[i] := N[i];')
[void]$sb.AppendLine('end;')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('end.')

[System.IO.File]::WriteAllText($out, $sb.ToString(), $enc)
"wrote $out ($($files.Count) skins: $($names -join ', '))"
