# Regenerate source/tyControls.BuiltinThemeData.pas from the built-in .tycss sources:
#   themes/auto.tycss      -> TyBuiltinDualBaseCss (the 'default' dual-mode base)
#   themes/system.tycss    -> TyBuiltinSystemCss   (the OS-accent 'system' theme)
#   themes/builtin/*.tycss -> the structural skins (classic/xp/office/win11/…), each compiled IN
# ALL of these are compiled into the binary so an app ships them with NO themes/ folder. The
# themes/builtin/ FILES are a REFERENCE copy for users to base their own themes on -- they are
# NOT scanned or dynamically loaded at runtime. Sync-tested byte-identical (test.builtinthemes).
# Run from the repo root:  powershell -File gen-builtinthemes.ps1
$ErrorActionPreference = 'Stop'
$enc = New-Object System.Text.UTF8Encoding($false)   # UTF-8, no BOM

function Emit-Func($name, $file) {
  $src = [IO.File]::ReadAllText($file, $enc)
  $lines = $src -split "`r`n|`n"
  if ($lines.Count -gt 0 -and $lines[-1] -eq '') { $lines = $lines[0..($lines.Count - 2)] }  # drop trailing empty
  $sb = New-Object System.Text.StringBuilder
  [void]$sb.Append("function $name`: string;`r`nbegin`r`n  Result :=`r`n")
  for ($i = 0; $i -lt $lines.Count; $i++) {
    $escd = $lines[$i] -replace "'", "''"
    if ($i -lt $lines.Count - 1) { $term = ' +' } else { $term = ';' }
    [void]$sb.Append("    '" + $escd + "' + LineEnding" + $term + "`r`n")
  }
  [void]$sb.Append("end;`r`n")
  return $sb.ToString()
}

# Discover the structural skins (sorted by file name).
$skinFiles = Get-ChildItem 'themes\builtin\*.tycss' | Sort-Object Name
$skinNames = @($skinFiles | ForEach-Object { [IO.Path]::GetFileNameWithoutExtension($_.Name) })

$u = New-Object System.Text.StringBuilder
[void]$u.Append("unit tyControls.BuiltinThemeData;`r`n`r`n")
[void]$u.Append("{ GENERATED by gen-builtinthemes.ps1 - do NOT edit by hand; edit the .tycss sources and`r`n")
[void]$u.Append("  re-run the generator. Compiles in the built-in themes so an app ships them with NO`r`n")
[void]$u.Append("  themes/ folder: themes/auto.tycss (the 'default' dual base), themes/system.tycss, and`r`n")
[void]$u.Append("  every structural skin in themes/builtin/*.tycss (classic/xp/office/win11/...). The`r`n")
[void]$u.Append("  themes/builtin/ FILES are a REFERENCE copy for users to base their own themes on -- they`r`n")
[void]$u.Append("  are NOT scanned at runtime. Sync-tested byte-identical to the files (test.builtinthemes). }`r`n`r`n")
[void]$u.Append("{`$mode objfpc}{`$H+}`r`n`r`ninterface`r`n`r`nuses SysUtils;`r`n`r`n")
[void]$u.Append("function TyBuiltinDualBaseCss: string;`r`nfunction TyBuiltinSystemCss: string;`r`n")
[void]$u.Append("{ The structural skin names (sorted) + each skin's compiled-in CSS by name ('' if unknown). }`r`n")
[void]$u.Append("function TyBuiltinSkinNames: TStringArray;`r`nfunction TyBuiltinSkinCss(const AName: string): string;`r`n`r`n")
[void]$u.Append("implementation`r`n`r`n")
[void]$u.Append((Emit-Func 'TyBuiltinDualBaseCss' 'themes\auto.tycss'))
[void]$u.Append("`r`n")
[void]$u.Append((Emit-Func 'TyBuiltinSystemCss' 'themes\system.tycss'))
[void]$u.Append("`r`n")
# One private function per skin (defined before the dispatcher that calls them).
foreach ($f in $skinFiles) {
  $name = [IO.Path]::GetFileNameWithoutExtension($f.Name)
  [void]$u.Append((Emit-Func "SkinCss_$name" $f.FullName))
  [void]$u.Append("`r`n")
}
# Sorted names array.
$arr = ($skinNames | ForEach-Object { "'$_'" }) -join ', '
[void]$u.Append("function TyBuiltinSkinNames: TStringArray;`r`n")
[void]$u.Append("const N: array[0..$($skinNames.Count - 1)] of string = ($arr);`r`n")
[void]$u.Append("var i: Integer;`r`nbegin`r`n  SetLength(Result, Length(N));`r`n  for i := 0 to High(N) do Result[i] := N[i];`r`nend;`r`n`r`n")
# Name -> CSS dispatcher.
[void]$u.Append("function TyBuiltinSkinCss(const AName: string): string;`r`nbegin`r`n")
foreach ($name in $skinNames) {
  [void]$u.Append("  if SameText(AName, '$name') then Exit(SkinCss_$name);`r`n")
}
[void]$u.Append("  Result := '';`r`nend;`r`n`r`n")
[void]$u.Append("end.`r`n")
[IO.File]::WriteAllText('source\tyControls.BuiltinThemeData.pas', $u.ToString(), $enc)
Write-Output "Regenerated BuiltinThemeData.pas (auto + system + $($skinNames.Count) skins: $($skinNames -join ', '))"
