program tytests;

{$mode objfpc}{$H+}

uses
  Interfaces, consoletestrunner, Graphics, Forms, tyControls.Painter, tyControls.Controller,
  tyControls.Calendar,
  test.Types, test.Css.Tokens, test.Css.Lexer, test.Css.Parser,
  test.Css.Values, test.StyleModel, test.accent, test.gradient, test.bevelborder, test.nineslice, test.metric, test.glyph, test.skins, test.fontcascade, test.darktext, test.painter, test.controller,
  test.controller.hotreload, test.base,
  test.baseevents,
  test.eventfiring,
  test.base.drawframe, test.formgradientbg, test.button, test.skinfit, test.englishfit, test.utf8, test.designeditors, test.focus.tabstop, test.tylabel, test.edit, test.edit.word, test.edit.undo, test.numericedit, test.currencyedit, test.maskedit, test.urledit, test.comboedit, test.trackedit, test.colorbox, test.colorcombobox, test.colorlistbox, test.fontcombobox, test.fontlistbox, test.fontfamilies, test.fontsizecombobox, test.checklistbox,
  test.mrucombobox, test.comboboxex, test.officelistbox, test.officecombobox, test.colorgrid, test.lcolorpicker,
  test.hscolorpicker, test.advancedlistbox, test.advancedcombobox, test.checkcombobox, test.valuelisteditor,
  test.calculator, test.calcedit,
  test.bevel, test.divider, test.paintpanel, test.sizebox,
  test.radiogroup, test.checkgroup, test.toolgrouppanel,
  test.scrollbox, test.scrollpanel, test.expanel,
  test.gridpanel, test.gridcell, test.relativepanel,
  test.toolbarex, test.controlbar, test.coolbar,
  test.headercontrol, test.listgrouppanel, test.listgrouppanel.entries,
  test.listgrouppanel.editor, test.structureeditors,
  test.checkbox,
  test.radiobutton, test.controls.panel, test.controls.combobox,
  test.controls.scrollbar,
  test.scrollbar.autohide,
  test.scrollbar.hostframe,
  test.form, test.titlebar.menuicon, test.formsurface, test.formsurface.cache, test.newproject, test.edgepassthrough, test.release, test.themes,
  test.listbox, test.listbox.scroll,
  test.progressbar,
  test.toggleswitch,
  test.trackbar,
  test.groupbox,
  test.tabstrip, test.tabstrip.axis, test.tabstrip.multiline,
  test.defaulttheme, test.spinedit, test.memo, test.memo.selection, test.memo.undo,
  test.floatspinedit, test.spinbuttons, test.freewhileownerlives, test.danglingrefs, test.translatable, test.componentleaks, test.examplelfm,
  test.memo.props,
  test.memo.visualrows,
  test.memo.hscroll,
  test.memo.wrap,
  test.memo.wrap.nav,
  test.memo.bidi,
  test.animation,
  test.animation.toggle,
  test.animation.button,
  test.undostack,
  test.themeregistry,
  test.themebundle,
  test.systemtheme,
  test.themelint,
  test.menu,
  test.builtinthemes,
  test.builtinskins,
  test.modecoherence,
  test.paletteicons,
  test.appicon,
  test.trailingzone,
  test.glyphthickness,
  test.lucide, test.glyphnames,
  test.virtualimagelist.iconfont,
  test.virtualimagelist.baked,
  test.imagedraw,
  test.imagename,
  test.css.catalog,
  test.controller.styleoverride,
  test.tabsheet,
  test.pagecontrol,
  test.pagecontrol.streaming,
  test.version,
  test.windoweffects,
  test.accel,
  test.i18n, test.paintcost, test.measurecache, test.memo.linesadd, test.parity, test.parity.valuelist, test.parity.splitter, test.parity.listview, test.parity.memo, test.parity.toolbar, test.parity.maskedit, test.parity.shelldivider, test.parity.grid, test.parity.ranges, test.parity.menu, test.parity.header, test.parity.onpaint, test.parity.spincheck,
  test.controller.changelistener,
  test.nativestyler,
  test.splitter,
  test.statusbar,
  test.toolbar,
  test.toolbar.paintbutton,
  test.litetrio.events,
  test.datetime.events,
  test.popup,
  test.calendar,
  test.datetimepicker,
  test.treeview.events,
  test.treeview,
  test.treeview.columns,
  test.treeview.streaming,
  test.treeview.items,
  test.treeview.edit,
  test.treeview.drag,
  test.dialogs,
  test.dialogs.chrome, test.dialogfit,
  test.dialogs.selectpath, test.dialogs.iconbrowser, test.dialogs.imagecollectioneditor,
  test.colormath,
  test.dialogs.color,
  test.dialogs.font,
  test.dialogs.find,
  test.dialogs.progress,
  test.dialogs.about,
  test.gauge,
  test.circularprogress,
  test.activityindicator,
  test.activitybar,
  test.meter,
  test.levelmeter,
  test.dial,
  test.analogclock,
  test.sparkline,
  test.rating,
  test.gearactivityindicator,
  test.updown,
  test.geardial,
  test.linklabel,
  test.shadowlabel,
  test.glowlabel,
  test.hint,
  test.balloonhint,
  test.iconfont,
  test.charimage,
  test.glyphimagelist,
  test.image,
  test.imagecollection,
  test.imagecollection.streaming,
  test.glyphbuttons,
  test.dropbuttons,
  test.colorbutton,
  test.buttongroup,
  test.ribbon,
  test.ribbonappmenu,
  test.ribbonquickaccess,
  test.ribbongallery,
  test.ribbonbackstage,
  test.popupsurface,
  test.keytips,
  test.combobox,
  test.combobox.simple,
  test.tabset,
  test.columns.compat,
  test.listview.layout,
  test.listview,
  test.filesystem,
  test.shelllistview,
  test.shelltreeview,
  test.filtercombobox,
  test.shellcombobox,
  test.dialogs.filedialog,
  test.previewbox,
  test.imageview,
  test.chart,
  test.advchart.types, test.advchart.scale, test.advchart.scale.break,
  test.advchart.scale.ordinal,
  test.advchart.coord, test.advchart.layout,
  test.painter.vector,
  test.advchart.axis,
  test.advchart.measure,
  test.advchart.shape, test.advchart.paint, test.advchart.marks, test.advchart.barlayout, test.advchart.stack, test.advchart.symbol, test.advchart.pie, test.advchart.title, test.advchart.labels, test.advchart.pielabel, test.advchart.legend, test.advchart.dataset, test.advchart.furniture, test.advchart.color, test.advchart.multiaxis, test.advchart.time, test.advchart.axislabel, test.advchart.gallery, test.advchart.hostileoptions, test.advchart.hit, test.advchart.tooltip, test.advchart.axispointer, test.advchart.emphasis, test.advchart.candlestick, test.advchart.funnel, test.advchart.gauge, test.advchart.radar, test.advchart.pictorial, test.advchart.graph, test.advchart.graphforce, test.advchart.graphlegend, test.advchart.graphcartesian, test.advchart.valueaxis, test.advchart.labeltext, test.advchart.seriestext, test.advchart.bargeometry, test.advchart.gridbounds, test.advchart.axisnames, test.advchart.jsmath, test.advchart.labelthinning, test.advchart.containshape, test.advchart.coordaffine, test.advchart.categoryminmax, test.advchart.graphroam, test.advchart.graphfocus, test.advchart.insidelabel, test.advchart.scalealign, test.advchart.rawvalue, test.advchart.subrows, test.advchart.boxmerge, test.advchart.parsevalue, test.advchart.visualmap, test.advchart.visualmapview, test.advchart.visualmapchannels, test.advchart.visualmappiecewise, test.advchart.visualmappiecewiseview, test.advchart.datazoomwindow, test.advchart.datazoomslider, test.advchart.datazoominteract, test.advchart.linesmooth, test.advchart.markerslayout, test.advchart.markline, test.advchart.markpoint, test.advchart.markarea, test.advchart.heatmap, test.advchart.calendar, test.advchart.heatmapcal, test.advchart.seriescal, test.advchart.tree, test.advchart.treeinteract, test.advchart.handlerwiring, test.advchart.textstyle, test.advchart.mouseevents, test.advchart.richtext, test.advchart.richwiring, test.advchart.sunburst, test.advchart.treemap, test.advchart.sankey, test.advchart.select, test.advchart.focusblur, test.advchart.legendact, test.advchart.legendscroll, test.advchart.tooltipfinish, test.advchart.axisfinish, test.advchart.animengine, test.advchart.animenter, test.advchart.animupdate, test.advchart.animlabels, test.advchart.optionmerge, test.advchart.animstate, test.advchart.animfullupdate, test.advchart.animmerge, test.advchart.sampling, test.advchart.timeformat, test.advchart.palettefill, test.advchart.exportloading, test.advchart.media, test.advchart.candleboxplot, test.advchart.labellayout, test.advchart.convertjitter, test.advchart.polaraxes, test.advchart.pieavoid, test.advchart.labelline,
  test.advchart.render,
  test.subpixel,
  test.advchart.option,
  test.advchart.catalog,
  test.advchart.complete,
  test.advchart.locate,
  test.advchart.diagnose,
  test.advchart.handlers,
  test.advchart.data,
  test.advchart.builder,
  test.advchart.series,
  test.advchart.style,
  test.advancechart,
  test.unicode.width,
  test.terminal.oracle, test.terminal.parser, test.terminal.buffer, test.terminal.core,
  test.terminal.keyboard, test.terminal.render, test.terminal.view, test.terminal.view.paint,
  test.terminal.view.input, test.terminal.view.theme, test.terminal.example,
  test.terminal.selection, test.terminal.links, test.terminal.view.mouse,
  test.terminal.view.links, test.terminal.pty, test.terminal.reflow, test.terminal.perf,
  test.terminal.colorscheme, test.terminal.view.scheme,
  test.terminal.stream, test.terminal.hooks, test.terminal.view.stream, test.terminal.zmodem, test.terminal.zmodem.wsl,
  test.terminal.view.flicker,
  test.transitions,
  test.htmllabel,
  test.shape,
  test.starshape,
  test.arrow,
  test.parity.shapearrow,
  test.parity.starshape,
  test.parity.image,
  test.parity.shell,
  test.parity.numeric,
  test.parity.treeview,
  test.parity.grid.members,
  test.parity.barsmenus,
  test.parity.container,
  test.parity.buttons,
  test.parity.listtext,
  test.parity.combo,
  test.combohint,
  test.bidi,
  test.rtl,
  test.edit.bidi,
  test.rtl.bars,
  test.rtl.chrome,
  test.card, test.tag, test.badge,
  test.grid.layout, test.grid, test.grid.streaming, test.grid.bidi,
  test.grid.objects, test.grid.options,
  test.alert, test.notification, test.empty, test.segmented,
  test.pagination, test.steps, test.breadcrumb, test.transfer,
  test.treeselect, test.cascader, test.popover,
  test.toolwindow.geometry, test.toolwindow.theme, test.toolwindow.window,
  test.toolwindow.actions, test.toolwindow.bar, test.toolwindow.images,
  test.toolwindow.focus, test.toolwindow.strip, test.toolwindow.edge,
  test.toolwindow.reorder, test.toolwindow.bottom, test.toolwindow.manager,
  test.toolwindow.crossdrag, test.toolwindow.layouttext, test.toolwindow.layoutapply,
  test.toolwindow.design, test.toolwindow.disabled, test.toolwindow.badge,
  test.toolwindow.hide,
  test.dpi.fontlatch, test.dpi.measurefont, test.dpi.containers, test.dpi.controls,
  test.dpi.dialogs, test.dpi.snapshot,
  test.parity.datetime,
  test.themebuilder.golden,
  test.themebuilder.parser,
  test.themebuilder.lint,
  test.themebuilder.editkit,
  test.themebuilder.doc,
  test.themebuilder.problems,
  test.themebuilder.preview,
  test.themebuilder.main,
  test.themebuilder.scan,
  test.themebuilder.seeds,
  test.themebuilder.pick,
  test.themebuilder.export,
  test.themebuilder.snippets,
  test.themebuilder.http,
  test.themebuilder.sse,
  test.themebuilder.aiclient,
  test.themebuilder.reference,
  test.themebuilder.diff,
  test.themebuilder.aisession,
  test.themebuilder.compare,
  test.themebuilder.edit,
  test.customclasses, test.customclasses.p1, test.customclasses.p2, test.customclasses.p3,
  test.customclasses.p4,
  test.typekeychain,
  test.db.common,
  test.corehooks;

type
  TTyTestRunner = class(TTestRunner)
  protected
  end;

var
  Application: TTyTestRunner;

begin
  // Headless determinism: keep the empty-FontName render path so position-
  // sensitive pixel tests are unaffected by the real system font. Disable the
  // controller's system-font fallback BEFORE any controller is created, and
  // force the fallback name empty. (The runner links the LCL widgetset, so
  // Screen.SystemFont is real here -- without this gate it would leak in.)
  TyAutoSystemFontFallback := False;
  TyFallbackFontName := '';
  // Same reason, second source of machine-dependence: TTyCalendar.FirstDayOfWeek
  // defaults to wdLocaleDefault, which tyControls.Calendar resolves from the OS at
  // unit start. Every calendar geometry assertion would otherwise be measuring the
  // developer's Control Panel -- a Monday-first machine shifts the whole day grid by
  // one column. Pin it here so a new calendar test cannot inherit the machine's
  // answer by omission; the one test that is ABOUT locale resolution overrides this
  // variable itself and restores it.
  //
  // The THIRD source of machine-dependence -- month/weekday NAMES -- needs no pin
  // here, because its default already resolves deterministically in this process:
  // TyDateTimeNameSource = dnAuto renders DefaultFormatSettings' names unless a
  // catalogue is loaded, and no test leaves one loaded (test.calendar's
  // TearDown restores the rsTyDateTimeNamesLang sentinel it translates; the
  // AutoWithNothingLoadedFollowsTheLocale precondition enforces the contract).
  // A test whose ASSERTION mentions a month or weekday name must not read the
  // machine's names into its expected value blind: either force
  // TyDateTimeNameSource := dnTranslation (fixed English resourcestrings,
  // machine-independent) or pin DefaultFormatSettings locally -- save, poke,
  // restore, as test.chart does for the numeric separators. Both knobs are
  // plain globals precisely so tests can inject them.
  TyLocaleFirstDayOfWeek := wdSunday;
  // FOURTH: the SCREEN. LCL creates every TFont at ScreenInfo's PPI, a form built with
  // CreateNew keeps the one it was born with, and its ParentFont children take it over --
  // so the screen decides the PPI of every control a test did not pin. Nothing in this
  // console process ever initialises ScreenInfo, which left it at the LCL default of 72:
  // a desktop nobody has, on which every unpinned form laid itself out at 75%. Make it the
  // 96-PPI desktop the expectations in these suites are written for. A test that is ABOUT
  // another scaling sets these itself and puts them back (tests/test.dpi.measurefont).
  ScreenInfo.PixelsPerInchX := 96;
  ScreenInfo.PixelsPerInchY := 96;
  Screen.UpdateScreen;
  Application := TTyTestRunner.Create(nil);
  Application.Initialize;
  Application.Title := 'TyControls Test Runner';
  Application.Run;
  Application.Free;
end.
