// Writes source/tyControls.Terminal.Luminance.inc and tests/fixtures/terminal-contrast.json
// from xterm.js 6.0.0 (pin and loading: lib-dump.js): what the terminal's minimum-contrast
// functions (tyControls.Terminal.Render / Core) are held to.
//
//   node tools/terminal-oracle/contrast-cases.js
//
// WHY A TABLE FOR THE LUMINANCE. src/common/Color.ts rgb.relativeLuminance2 linearizes
// each sRGB channel with Math.pow(x, 2.4). V8's pow is not correctly rounded and FPC's
// Power is a different routine again; ensureContrastRatio compares `cr < ratio` and
// loops in 10 % steps, so one ulp at a boundary is one more step and another colour.
// There are only 256 channel values: node computes each one with upstream's own
// expression, the include holds the IEEE bit patterns, and the Pascal side sums
// t[r] * 0.2126 + t[g] * 0.7152 + t[b] * 0.0722 in the same order. Before writing, the
// table is proved on 100000 seeded random colours: the sum must be Object.is-equal to
// upstream's relativeLuminance2(r, g, b) -- or the script stops.
//
// The fixture (colours are 0xRRGGBB numbers, doubles are their IEEE bits as 16 hex
// digits, most significant first):
//   luminance  [rgb, bits] for Tango's 16, the light ground's 12 (light-palette.js's
//              own output, not recomputed), the 24 greys and 2000 seeded random colours
//   ratios     the nine ratios of `ensure`
//   ensure     [bg, fg, [result per ratio]] -- rgba.ensureContrastRatio(bg, fg, ratio);
//              null where upstream answers undefined (the ratio already holds). Pairs:
//              every two of Tango 16 + light 12 + greys 24 + black + white, and 3000
//              seeded random pairs
//   reduce / increase  [bg, fg, ratio, result]: 500 random pairs x 4.5 and 7
//   clamp      [value as given, bits after] through OptionsService's own setter
//   excluded   [first, last] runs of treatGlyphAsBackgroundColor(cp) over
//              U+2400-2700 and U+E000-E100 (the ranges scanned are in "scanned")
//
// The include's header carries the upstream version, commit and commit date, never
// the time of the run; it holds no brace (checked -- a brace opens a nested comment
// in FPC).
'use strict';
const path = require('path');
const cp = require('child_process');
const L = require('./lib-dump.js');

const up = L.loadUpstream();
const C = require(path.join(L.XTERM, L.OUT_DIR, 'common/Color.js'));
const { DEFAULT_ANSI_COLORS } = require(path.join(L.XTERM, L.OUT_DIR, 'browser/Types.js'));
const RU = require(path.join(L.XTERM, L.OUT_DIR, 'browser/renderer/shared/RendererUtils.js'));
const { OptionsService } = require(path.join(L.XTERM, L.OUT_DIR, 'common/services/OptionsService.js'));

const bits = x => {
  const b = Buffer.alloc(8);
  b.writeDoubleBE(x);
  return b.toString('hex');
};

// ---- the table ----------------------------------------------------------------------
// Color.ts:250-255, the same expression per channel value
const table = [];
for (let c = 0; c < 256; c++) {
  const s = c / 255;
  table.push(s <= 0.03928 ? s / 12.92 : Math.pow((s + 0.055) / 1.055, 2.4));
}

let seed = 20260929;
function rnd() {
  seed ^= seed << 13; seed >>>= 0;
  seed ^= seed >>> 17;
  seed ^= seed << 5; seed >>>= 0;
  return seed;
}
const rndColor = () => rnd() & 0xFFFFFF;

for (let k = 0; k < 100000; k++) {
  const r = rnd() & 0xFF, g = rnd() & 0xFF, b = rnd() & 0xFF;
  const mine = table[r] * 0.2126 + table[g] * 0.7152 + table[b] * 0.0722;
  const theirs = C.rgb.relativeLuminance2(r, g, b);
  if (!Object.is(mine, theirs)) {
    console.error(`the table is not upstream's luminance: ${r},${g},${b} -> ${mine} vs ${theirs}`);
    process.exit(1);
  }
}

const i = up.info;
const header = [
  'GENERATED by tools/terminal-oracle/contrast-cases.js -- do NOT edit by hand;',
  'change the script and rerun it. Upstream: xterm.js ' + i.version + ', commit ' + i.commit,
  `(${i.commitDate}), src/common/Color.ts rgb.relativeLuminance2.`,
  '',
  'TyTermLinearChannelBits[c]: the IEEE bits of the linearized sRGB channel c / 255,',
  '  as upstream computes it in V8 (s <= 0.03928 ? s / 12.92 :',
  '  pow((s + 0.055) / 1.055, 2.4)) -- a table because pow is not correctly rounded',
  '  and FPC\'s Power differs; proved against relativeLuminance2 on 100000 colours.',
  '',
  'Derived from xterm.js, MIT:',
  '  Copyright (c) 2017 The xterm.js authors (src/common/Color.ts)',
  'Full text: THIRD-PARTY-NOTICES.md.',
];
let out = header.map(l => ('// ' + l).trimEnd()).join('\n') + '\n\nconst\n';
out += '  TyTermLinearChannelBits: array[0..255] of QWord = (\n';
const rows = [];
for (let k = 0; k < 256; k += 4) {
  rows.push('    ' + table.slice(k, k + 4).map(x => '$' + bits(x).toUpperCase()).join(', '));
}
out += rows.join(',\n') + ');\n';
if (/[{}]/.test(out)) throw new Error('a brace in the generated include');
L.writeGenerated('source/tyControls.Terminal.Luminance.inc', out);

// ---- the colours --------------------------------------------------------------------
const ansi = DEFAULT_ANSI_COLORS.map(c => c.rgba >>> 8);
const tango = ansi.slice(0, 16);
const greys = ansi.slice(232, 256);
// light-palette.js's output: " i  #tango  ->  #light  ratio"; the 12 it changed or
// checked (1-6, 9-14), as it printed them
const lp = cp.execFileSync(process.execPath, [path.join(__dirname, 'light-palette.js')], { encoding: 'utf8' });
const light = [];
for (const line of lp.split('\n')) {
  const m = line.match(/^\s*(\d+)\s+#([0-9a-f]{6})\s+->\s+#([0-9a-f]{6})\s/);
  if (!m) continue;
  const n = +m[1];
  if ((n >= 1 && n <= 6) || (n >= 9 && n <= 14)) light.push(parseInt(m[3], 16));
}
if (light.length !== 12) throw new Error('light-palette.js gave ' + light.length + ' light-ground colours');
if (!light.includes(0x8e7400)) throw new Error('light-palette.js: no #8e7400 for colour 3');

const luminance = [];
const lumOf = rgbv => [rgbv, bits(C.rgb.relativeLuminance(rgbv))];
for (const c of [...tango, ...light, ...greys]) luminance.push(lumOf(c));
for (let k = 0; k < 2000; k++) luminance.push(lumOf(rndColor()));

const RATIOS = [1, 1.5, 2.25, 3, 3.5, 4.5, 7, 10.5, 21];
const ensureOne = (bg, fg) => [bg, fg, RATIOS.map(r => {
  const v = C.rgba.ensureContrastRatio(((bg << 8) | 0xFF) >>> 0, ((fg << 8) | 0xFF) >>> 0, r);
  return v === undefined ? null : (v >>> 8);
})];
const set = [...tango, ...light, ...greys, 0x000000, 0xFFFFFF];
const ensure = [];
for (const bg of set) for (const fg of set) ensure.push(ensureOne(bg, fg));
for (let k = 0; k < 3000; k++) ensure.push(ensureOne(rndColor(), rndColor()));

// the spot check of the plan: white ground, Tango 3, 4.5 -> #8e7400
const spot = C.rgba.ensureContrastRatio(0xFFFFFFFF, ((0xc4a000 << 8) | 0xFF) >>> 0, 4.5) >>> 8;
if (spot !== 0x8e7400) throw new Error('white, Tango 3, 4.5 gave ' + spot.toString(16));

const reduce = [], increase = [];
for (let k = 0; k < 500; k++) {
  const bg = rndColor(), fg = rndColor();
  for (const r of [4.5, 7]) {
    const b = ((bg << 8) | 0xFF) >>> 0, f = ((fg << 8) | 0xFF) >>> 0;
    reduce.push([bg, fg, r, C.rgba.reduceLuminance(b, f, r) >>> 8]);
    increase.push([bg, fg, r, C.rgba.increaseLuminance(b, f, r) >>> 8]);
  }
}

const CLAMP = [-5, 0, 0.5, 1, 1.04, 1.05, 1.15, 1.25, 1.35, 4.45, 4.449999, 4.5, 7.35, 20.96, 21, 21.04, 22, 1e9];
const opts = new OptionsService({});
const clamp = CLAMP.map(v => {
  opts.options.minimumContrastRatio = v;
  return [v, bits(opts.options.minimumContrastRatio)];
});

const SCANNED = [[0x2400, 0x2700], [0xE000, 0xE100]];
const excluded = [];
for (const [a, b] of SCANNED) {
  let start = -1;
  for (let c = a; c <= b + 1; c++) {
    const on = c <= b && RU.treatGlyphAsBackgroundColor(c);
    if (on && start < 0) start = c;
    if (!on && start >= 0) { excluded.push([start, c - 1]); start = -1; }
  }
}

L.writeFixture('terminal-contrast.json', {
  upstream: up.info, generator: 'tools/terminal-oracle/contrast-cases.js', kind: 'contrast',
  luminance, ratios: RATIOS, ensure, reduce, increase, clamp, scanned: SCANNED, excluded,
});
console.log(`luminance ${luminance.length}, ensure ${ensure.length} pairs x ${RATIOS.length}, reduce ${reduce.length}, ` +
  `increase ${increase.length}, clamp ${clamp.length}, excluded ${JSON.stringify(excluded.map(r => r.map(x => x.toString(16))))}`);
process.exit(0);
