// Inputs for keyboard-cases.js -- only inputs; every expected value comes from
// xterm.js. The full combination sweep (every US-layout key x 16 modifier sets x
// application cursor x platform) is generated by keyboard-cases.js from its layout
// table; what is here are the events LCL cannot produce but evaluateKeyboardEvent
// has branches for, and the paste texts.
'use strict';

const ev = (keyCode, key, code, mods = '') => ({
  keyCode, key, code,
  shift: mods.includes('S'), alt: mods.includes('A'), ctrl: mods.includes('C'), meta: mods.includes('M'),
});

// Each hand event runs with application cursor off and on, on the three platform
// settings (win, mac, macMeta).
const hand = [
  // Safari on iOS / iPadOS: arrows arrive as keyCode 0 with these key names
  { id: 'ios-up', ev: ev(0, 'UIKeyInputUpArrow', '') },
  { id: 'ios-left', ev: ev(0, 'UIKeyInputLeftArrow', '') },
  { id: 'ios-right', ev: ev(0, 'UIKeyInputRightArrow', '') },
  { id: 'ios-down', ev: ev(0, 'UIKeyInputDownArrow', '') },
  { id: 'ios-other', ev: ev(0, 'Unidentified', '') },
  // Safari's Ctrl+C as keyCode 13
  { id: 'enter-key-c-ctrl', ev: ev(13, 'c', 'KeyC', 'C') },
  { id: 'enter-key-c-plain', ev: ev(13, 'c', 'KeyC') },
  // macOS Option producing a dead key (issue 3725): keyCode 229, code KeyN / KeyE
  { id: 'dead-n-alt', ev: ev(229, 'Dead', 'KeyN', 'A') },
  { id: 'dead-n-alt-shift', ev: ev(229, 'Dead', 'KeyN', 'SA') },
  { id: 'dead-e-alt', ev: ev(229, 'Dead', 'KeyE', 'A') },
  { id: 'dead-e-alt-shift', ev: ev(229, 'Dead', 'KeyE', 'SA') },
  { id: 'dead-digit-alt', ev: ev(229, 'Dead', 'Digit6', 'A') },
  // Ctrl+/ by key, not by keyCode (issue 5457)
  { id: 'ctrl-slash-191', ev: ev(191, '/', 'Slash', 'C') },
  { id: 'ctrl-slash-55', ev: ev(55, '/', 'Digit7', 'C') },
  // characters a layout produces, one UTF-16 unit or two
  { id: 'e-acute', ev: ev(69, 'é', 'KeyE') },
  { id: 'euro', ev: ev(69, '€', 'KeyE') },
  { id: 'emoji', ev: ev(69, '\u{1F600}', 'KeyE') },
  { id: 'cjk', ev: ev(69, '中', 'KeyE') },
  // what Option+A types on macOS
  { id: 'option-a', ev: ev(65, 'å', 'KeyA', 'A') },
  { id: 'option-shift-a', ev: ev(65, 'Å', 'KeyA', 'SA') },
];

// Third-level shift: keys (a VK and its modifiers, the key and code from the layout
// table; VK 0 is outside it) swept again with getModifierState('AltGraph') true --
// Windows reports it for AltGr, which also sets Ctrl and Alt.
const altGraph = [
  [81, 'CA'], [81, ''], [69, 'CA'], [55, 'CA'], [55, 'SCA'], [37, 'CA'], [8, 'CA'], [0, 'CA'],
  [0, ''], [81, 'CAM'], [219, 'CA'],
];

const paste = [
  '', 'a', 'a\nb', 'a\r\nb', 'a\rb', 'a\n\nb', 'a\r\n\r\nb', '\x1b[201~evil', '中文\n\u{1F600}',
  '\x1b\x1b', '\n', '\r\n', 'tab\there', 'x\x1b[200~y\x1b[201~z',
];

module.exports = { hand, altGraph, paste };
