"""Writes tools/painter-regress/pr_classes.pas: every class the library's units declare
at the top of their interface section, registered by name, so that the example form
files can be read through a real TReader without the design-time package (the
test runner gets the same from its many test units).

    python tools/painter-regress/gen-classes.py

The platform units that do not build on Windows (Cocoa, GTK2, GTK3) are left out; a
class that is not a TPersistent is skipped at run time (RegisterClass needs one).
Rerun after adding a unit or a control; the file is generated, do not edit it."""
import os
import re

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..'))
SRC = os.path.join(ROOT, 'source')
SKIP = {'tyControls.CocoaWS', 'tyControls.Gtk2WS', 'tyControls.Gtk3WS'}

units = sorted(f[:-4] for f in os.listdir(SRC) if f.startswith('tyControls.') and f.endswith('.pas')
               and f[:-4] not in SKIP)
names = []
seen = set()
dup = set()
for u in units:
    text = open(os.path.join(SRC, u + '.pas'), encoding='utf-8', errors='replace').read()
    m = re.search(r'(?mi)^interface\b(.*?)^implementation\b', text, re.S)
    if not m:
        continue
    for c in re.findall(r'(?m)^  (T\w+)\s*=\s*class\s*\(', m.group(1)):
        if c in seen:
            dup.add(c)
        seen.add(c)
        names.append(c)
names = [c for c in names if c not in dup]

out = ['unit pr_classes;',
       '{$mode objfpc}{$H+}',
       '{ GENERATED by tools/painter-regress/gen-classes.py -- do not edit; rerun the script.',
       '  Every class the library\'s units declare at the top of their interface, registered by',
       '  name for the form reader (the ones that are not TPersistent are skipped). }',
       '',
       'interface',
       '',
       'procedure PrRegisterClasses;',
       '',
       'implementation',
       '',
       'uses',
       '  Classes,']
for k, u in enumerate(units):
    out.append('  ' + u + (';' if k == len(units) - 1 else ','))
out += ['',
        'procedure Reg(AClass: TClass);',
        'begin',
        '  if AClass.InheritsFrom(TPersistent) then',
        '    RegisterClass(TPersistentClass(AClass));',
        'end;',
        '',
        'procedure PrRegisterClasses;',
        'begin']
for c in names:
    out.append('  Reg(' + c + ');')
out += ['end;', '', 'end.', '']
open(os.path.join(ROOT, 'tools', 'painter-regress', 'pr_classes.pas'), 'w', encoding='utf-8', newline='\n').write(
    '\n'.join(out))
print(len(units), 'units,', len(names), 'classes,', len(dup), 'duplicate names left out')
