# Generates source/tyControls.Css.Catalog.pas -- the machine-readable tycss vocabulary
# (token names + typeKeys) that the design-time StyleOverride editor completes against.
#
# Source of truth = themes/light.tycss (the base theme where every token is declared and every
# typeKey is a selector head). Property names, colour functions and pseudo-states are NOT here --
# those are closed sets pinned in code (TyKnownStyleProps / TyKnownColorFns / TyKnownPseudoStates),
# and the aggregate accessor in the generated unit re-exports them so the editor has one door.
#
# Re-run after editing themes/light.tycss. test.css.catalog asserts the output matches the source,
# so a stale catalog is a red test, not a silent gap.
$ErrorActionPreference = 'Stop'
$root  = Split-Path $PSScriptRoot -Parent
$light = Join-Path $root 'themes/light.tycss'
$out   = Join-Path $root 'source/tyControls.Css.Catalog.pas'

# De-duplicate AND sort ORDINALLY (by byte value), so the emitted order is exactly Pascal's `<`
# on strings -- test.css.catalog asserts that ascending order, which PowerShell's default
# culture-aware Sort-Object (case-insensitive, hyphen-folding) would violate.
function Sort-OrdinalUnique($items) {
  $set = New-Object 'System.Collections.Generic.SortedSet[string]' (, [System.StringComparer]::Ordinal)
  foreach ($x in $items) { [void]$set.Add($x) }
  return , ([string[]]$set)
}

# Read as real UTF-8 (PS 5.1 Get-Content -Raw decodes via the ANSI codepage and mangles the file).
$text = [System.IO.File]::ReadAllText($light)
# Strip /* ... */ comments so a typeKey named in prose is not mistaken for a selector head.
$src = [regex]::Replace($text, '/\*.*?\*/', '', 'Singleline')

# Tokens: every DEFINITION '--name:' anywhere (main :root + any @mode/rule-scoped block). A usage
# 'var(--name)' has ')' not ':' after the name, so it never matches.
$tokens = Sort-OrdinalUnique ([regex]::Matches($src, '--([a-z][a-z0-9-]*)\s*:') |
  ForEach-Object { '--' + $_.Groups[1].Value })

# typeKeys: word-bounded 'TyXxx' selector heads (the only place 'Ty' appears once comments are gone).
$typeKeys = Sort-OrdinalUnique ([regex]::Matches($src, '\bTy[A-Za-z][A-Za-z0-9]*\b') |
  ForEach-Object { $_.Value })

if ($tokens.Count -eq 0)   { throw "no --tokens found in $light -- regex or file wrong" }
if ($typeKeys.Count -eq 0) { throw "no TyXxx typeKeys found in $light" }

function Emit-Array([string]$name, $items) {
  $n = $items.Count
  $sb = New-Object System.Text.StringBuilder
  [void]$sb.AppendLine("  $name" + ": array[0.." + ($n - 1) + "] of string = (")
  for ($i = 0; $i -lt $n; $i++) {
    $sep = if ($i -lt $n - 1) { ',' } else { ');' }
    [void]$sb.AppendLine("    '" + $items[$i] + "'" + $sep)
  }
  return $sb.ToString().TrimEnd("`r", "`n")
}

$body = @"
unit tyControls.Css.Catalog;
{`$mode objfpc}{`$H+}

{ GENERATED by scripts/gen-tycss-catalog.ps1 from themes/light.tycss -- do NOT edit by hand.
  Change the theme and re-run the script. test.css.catalog guards the two against drift.

  The machine-readable tycss vocabulary for the design-time StyleOverride editor:
    - TyCatalogTokens   : the --custom-property names a theme defines ($($tokens.Count) of them).
                          OPEN axis -- a theme may invent more, so the editor SUGGESTS these but
                          must not reject an unknown one.
    - TyCatalogTypeKeys : the control selector heads ($($typeKeys.Count) of them), for the
                          controller-level (selector-carrying) override.

  Property names, colour functions and pseudo-states are closed sets and live in code beside their
  resolvers (tyControls.StyleModel.TyKnownStyleProps, tyControls.Css.Values.TyKnownColorFns,
  tyControls.Css.Parser.TyKnownPseudoStates); this unit is the token/typeKey half only. }

interface

const
$(Emit-Array 'TyCatalogTokens' $tokens)

$(Emit-Array 'TyCatalogTypeKeys' $typeKeys)

implementation

end.
"@

[System.IO.File]::WriteAllText($out, $body, (New-Object System.Text.UTF8Encoding($false)))
Write-Host ("Wrote {0}: {1} tokens, {2} typeKeys" -f $out, $tokens.Count, $typeKeys.Count)
