# Embeds assets/lucide/LICENSE verbatim into source/tyControls.Icons.Lucide.License.inc as the
# Pascal constant TyLucideLicense, so the design-time StyleOverride/License editor can show the
# full ISC + MIT (Feather) text with no external file at run time -- and it can never drift from
# the source file (test.lucide byte-checks the two). Re-run after editing assets/lucide/LICENSE.
$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
$lic  = Join-Path $root 'assets/lucide/LICENSE'
$out  = Join-Path $root 'source/tyControls.Icons.Lucide.License.inc'

# Read as real UTF-8 (PS 5.1 Get-Content -Raw decodes via the ANSI codepage). Normalise to LF so
# the emitted literal is stable across checkouts; split into lines for one Pascal literal each.
$text  = [System.IO.File]::ReadAllText($lic)
$lines = ($text -replace "`r`n", "`n").TrimEnd("`n") -split "`n"

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('{ GENERATED by scripts/gen-lucide-license.ps1 from assets/lucide/LICENSE --')
[void]$sb.AppendLine('  do NOT edit by hand. test.lucide byte-checks this against the source file.')
[void]$sb.AppendLine('  A bare const declaration (no `const` keyword) so it can be {$I}-included')
[void]$sb.AppendLine('  inside the generated unit''s existing const section. }')
[void]$sb.AppendLine('  TyLucideLicense =')
for ($i = 0; $i -lt $lines.Count; $i++) {
  # Double single quotes for Pascal; each source line becomes '<line>' + LineEnding (last: ';').
  $esc = $lines[$i] -replace "'", "''"
  $tail = if ($i -lt $lines.Count - 1) { " + LineEnding +" } else { ";" }
  [void]$sb.AppendLine("    '" + $esc + "'" + $tail)
}

[System.IO.File]::WriteAllText($out, $sb.ToString(), (New-Object System.Text.UTF8Encoding($false)))
Write-Host ("Wrote {0}: {1} lines" -f $out, $lines.Count)
